seed = 0
n_trials = 100
sampler_type = "BruteForceSampler"
function = "bin.graphpfn.evaluate.main"

[space]
seed = 0
amp = true
checkpoint_name = "hf://eremeev-d/graphpfn-1.3/graphpfn-adapters-1_3.pt"
unfreeze_all = true
n_steps = 0
epoch_size = 10
patience = 4
seq_len_pred = 1024
min_train_ratio = 0.75

[space.ensemble]
shuffle_features = false
shuffle_targets = false
n_members = 1

[space.model]
n_random_features = 8

[space.model.edge_head]

[space.data]
cache = false
path = "data/city-reviews"
setting = "transductive"
internal_split_name = "RL"

[space.transform]
labels = false

[space.transform.features]
seed = 0
cat_policy = "ordinal"
num_policy = "quantile-normal"
frac_policy = "quantile-uniform"

[space.optimizer]
type = "AdamW"
lr = 0.0003
weight_decay = 0.0
