function = "bin.lightgbm_.main"
n_seeds = 10

[base_config.data]
cache = false
path = "data/hm-prices"
setting = "transductive"
add_self_loops = false
num_policy = "none"
ratio_policy = "none"
cat_policy = "ordinal"
internal_split_name = "RL"

[base_config.data.nfa]

[base_config.model]
n_estimators = 4000
n_jobs = 4
verbose = -1
feature_fraction = 0.7413420244189157
lambda_l2 = 0.37941093315153185
learning_rate = 0.006862479249724589
num_leaves = 31
min_sum_hessian_in_leaf = 0.002328175107125372
bagging_fraction = 0.7439611751920455
stopping_rounds = 1000
device_type = "cpu"

[base_config.fit]
