[project]
name = "graphpfn"
version = "0.1.1"
description = "GraphPFN"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Dmitry Eremeev" },
    { name = "Oleg Platonov" },
    { name = "Gleb Bazhenov" },
    { name = "Artem Babenko" },
    { name = "Liudmila Prokhorenkova" },
]
requires-python = ">=3.11,<4"
dependencies = [
    "numpy>=2.0",
    "torch>=2.1,<2.5",
    "dgl>=2.4,<2.5",
    "scikit-learn>=1.4",
    "optuna>=3.1.0",
    "huggingface-hub",
    "einops",
    "torch-geometric",
    "tqdm",
    "pyyaml",
    "pandas",
    "delu",
]

[project.urls]
Repository = "https://github.com/eremeev-d/graphpfn-package"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/graphpfn"]

[dependency-groups]
dev = [
    "ruff>=0.9",
    "ty>=0.0.1a0",
]

[tool.hatch.build.targets.wheel.force-include]
"LICENSE" = "LICENSE"
"NOTICE" = "NOTICE"
"LICENSES" = "LICENSES"

[tool.ruff]
line-length = 88
extend-exclude = [
    "src/graphpfn/_vendor/**/*.py",
    "research",
]

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
extend-select = ["RUF", "UP", "E501", "E731"]

[tool.ruff.lint.isort]
known-first-party = ["graphpfn"]

[[tool.uv.index]]
name = "torch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
name = "dgl-cu118"
url = "https://data.dgl.ai/wheels/torch-2.4/cu118/repo.html"
format = "flat"
explicit = true

[tool.uv.sources]
torch = { index = "torch-cu118" }
dgl = { index = "dgl-cu118" }

[tool.ty.src]
exclude = [
    "src/graphpfn/_vendor",
    "research",
]
