function = "bin.lightgbm_.main"
n_seeds = 10

[base_config.data]
cache = false
path = "data/questions"
setting = "transductive"
add_self_loops = false
num_policy = "none"
external_split = true

[base_config.data.nfa]
num_modes = [
    "mean",
]

[base_config.data.pca.params]
dim = 1000000

[base_config.model]
n_estimators = 4000
n_jobs = 4
verbose = -1
feature_fraction = 0.5229727323659132
lambda_l2 = 0.0
learning_rate = 0.08703369564127438
num_leaves = 601
min_sum_hessian_in_leaf = 20.885569168873573
bagging_fraction = 0.6662675625303507
stopping_rounds = 1000
device_type = "cpu"

[base_config.fit]
