function = "bin.lightgbm_.main"
n_seeds = 10

[base_config.data]
cache = false
path = "data/twitch-views"
setting = "transductive"
add_self_loops = false
num_policy = "none"
ratio_policy = "none"
cat_policy = "ordinal"
internal_split_name = "RL"

[base_config.data.nfa]

[base_config.model]
n_estimators = 4000
n_jobs = 4
verbose = -1
feature_fraction = 0.5005331468789174
lambda_l2 = 0.1492866436049868
learning_rate = 0.002994184421383981
num_leaves = 45
min_sum_hessian_in_leaf = 0.0010948776672524006
bagging_fraction = 0.6611762827733308
stopping_rounds = 1000
device_type = "cpu"

[base_config.fit]
