seed = 0
function = "bin.g2t.g2t_fm.main"
n_trials = 100
sampler_type = "BruteForceSampler"

[space]
seed = 0
patience = 16
amp = true
n_epochs = 0
epoch_size = 10
min_train_ratio = 0.75
seq_len_pred = 1024
finetune_mode = "full"

[space.ensemble]
shuffle_features = true
shuffle_targets = false
n_members = 10

[space.tfm]
name = "limix"

[space.nfa]

[space.d_reduction]
method = "pca"
d = 64

[space.data]
cache = false
path = "data/city-reviews"
setting = "transductive"
internal_split_name = "RL"

[space.transform]
labels = false

[space.transform.features]
seed = 0
cat_policy = "ordinal"
num_policy = "quantile-normal"
frac_policy = "quantile-uniform"

[space.transform.nfa]
seed = 0
cat_policy = "ordinal"
num_policy = "quantile-normal"
frac_policy = "quantile-uniform"

[space.optimizer]
type = "AdamW"
lr = 0.0003
weight_decay = 0.0
