seed = 0
n_trials = 100
sampler_type = "BruteForceSampler"
function = "bin.graphpfn_evaluate.main"

[space]
seed = 0
amp = true
checkpoint_name = "graphpfn-v1"
unfreeze_all = true
n_steps = 0
epoch_size = 10
patience = 4
seq_len_pred = 1024
min_train_ratio = 0.75

[space.data]
cache = false
path = "data/pubmed"
setting = "transductive"
num_policy = "standard"
external_split = true

[space.optimizer]
type = "AdamW"
lr = 0.0003
weight_decay = 0.0
