function = "bin.graphpfn_evaluate.main"
n_seeds = 10

[base_config]
amp = true
checkpoint_name = "graphpfn-v1"
unfreeze_all = true
n_steps = -1
epoch_size = 10
patience = 4
seq_len_pred = 1024
min_train_ratio = 0.75

[base_config.data]
cache = false
path = "data/wiki-cs"
setting = "transductive"
num_policy = "standard"
external_split = true

[base_config.data.graph_encodings]
preprocess = "noisy-quantile-normal"

[base_config.data.graph_encodings.lap_pe]
k = 8

[base_config.optimizer]
type = "AdamW"
lr = 6.457747804233804e-05
weight_decay = 0.0
