function = "bin.lightgbm_.main"
n_seeds = 10

[base_config.data]
cache = false
path = "data/tolokers-2"
setting = "transductive"
add_self_loops = false
num_policy = "none"
ratio_policy = "none"
cat_policy = "ordinal"
internal_split_name = "RL"

[base_config.data.nfa]

[base_config.model]
n_estimators = 4000
n_jobs = 4
verbose = -1
feature_fraction = 0.7340045917722927
lambda_l2 = 0.0
learning_rate = 0.0012615535926116493
num_leaves = 89
min_sum_hessian_in_leaf = 6.076492545084748
bagging_fraction = 0.6800187553793567
stopping_rounds = 1000
device_type = "cpu"

[base_config.fit]
