function = "bin.lightgbm_.main"
n_seeds = 10

[base_config.data]
cache = false
path = "data/avazu-ctr"
setting = "transductive"
add_self_loops = false
num_policy = "none"
ratio_policy = "none"
cat_policy = "ordinal"
internal_split_name = "RL"

[base_config.data.nfa]

[base_config.data.pca.params]
dim = 1000000

[base_config.model]
n_estimators = 4000
n_jobs = 4
verbose = -1
feature_fraction = 0.7447641775271334
lambda_l2 = 3.3671988848484653
learning_rate = 0.0011579830996960023
num_leaves = 34
min_sum_hessian_in_leaf = 2.4977136027437368
bagging_fraction = 0.9199789862819325
stopping_rounds = 1000
device_type = "cpu"

[base_config.fit]
