max_ba_deg: 4
max_ba_nodes: 1000
max_first_level_sbm_graphs: 3
max_sbm_group_size: 1000
max_sbm_groups: 25
max_sbm_nodes: 2500
min_ba_nodes: 800
min_first_level_sbm_graphs: 2
min_sbm_group_size: 25
min_sbm_groups: 1
min_sbm_nodes: 2000
sbm_divisor: 1
