function = "bin.lightgbm_.main"
n_seeds = 10

[base_config.data]
cache = false
path = "data/artnet-views"
setting = "transductive"
add_self_loops = false
num_policy = "none"
ratio_policy = "none"
cat_policy = "ordinal"
internal_split_name = "RL"

[base_config.data.nfa]

[base_config.model]
n_estimators = 4000
n_jobs = 4
verbose = -1
feature_fraction = 0.5371234897689963
lambda_l2 = 5.658358942097257
learning_rate = 0.0036127342720581814
num_leaves = 695
min_sum_hessian_in_leaf = 35.23928173492347
bagging_fraction = 0.7418178795268486
stopping_rounds = 1000
device_type = "cpu"

[base_config.fit]
