function = "bin.lightgbm_.main"
n_seeds = 10

[base_config.data]
cache = false
path = "data/city-roads-M"
setting = "transductive"
add_self_loops = false
num_policy = "none"
ratio_policy = "none"
cat_policy = "ordinal"
internal_split_name = "RL"

[base_config.data.nfa]

[base_config.model]
n_estimators = 4000
n_jobs = 4
verbose = -1
feature_fraction = 0.5084950160316473
lambda_l2 = 8.54001209690827
learning_rate = 0.0016888107098926744
num_leaves = 69
min_sum_hessian_in_leaf = 16.49410547499806
bagging_fraction = 0.6296821454480814
stopping_rounds = 1000
device_type = "cpu"

[base_config.fit]
