function = "bin.lightgbm_.main"
n_seeds = 10

[base_config.data]
cache = false
path = "data/pubmed"
setting = "transductive"
add_self_loops = false
num_policy = "none"
external_split = true

[base_config.data.nfa]
num_modes = [
    "mean",
]

[base_config.data.pca.params]
dim = 1000000

[base_config.model]
n_estimators = 4000
n_jobs = 4
verbose = -1
feature_fraction = 0.9720065973503701
lambda_l2 = 0.6212891386390126
learning_rate = 0.003681537152244455
num_leaves = 535
min_sum_hessian_in_leaf = 0.0071850673920898205
bagging_fraction = 0.6638952086378977
stopping_rounds = 1000
device_type = "cpu"

[base_config.fit]
