function = "bin.lightgbm_.main"
n_seeds = 10

[base_config.data]
cache = false
path = "data/artnet-exp"
setting = "transductive"
add_self_loops = false
num_policy = "none"
ratio_policy = "none"
cat_policy = "ordinal"
internal_split_name = "RL"

[base_config.data.nfa]

[base_config.model]
n_estimators = 4000
n_jobs = 4
verbose = -1
feature_fraction = 0.5318315048936229
lambda_l2 = 0.0
learning_rate = 0.0010139714313629313
num_leaves = 470
min_sum_hessian_in_leaf = 5.0525407997973995
bagging_fraction = 0.6040011071315626
stopping_rounds = 1000
device_type = "cpu"

[base_config.fit]
