function = "bin.lightgbm_.main"
n_seeds = 10

[base_config.data]
cache = false
path = "data/city-reviews"
setting = "transductive"
add_self_loops = false
num_policy = "none"
ratio_policy = "none"
cat_policy = "ordinal"
internal_split_name = "RL"

[base_config.data.nfa]

[base_config.data.pca.params]
dim = 1000000

[base_config.model]
n_estimators = 4000
n_jobs = 4
verbose = -1
feature_fraction = 0.5001136726247335
lambda_l2 = 0.0
learning_rate = 0.0018206752257594778
num_leaves = 132
min_sum_hessian_in_leaf = 0.018036928327804975
bagging_fraction = 0.5438825594786084
stopping_rounds = 1000
device_type = "cpu"

[base_config.fit]
