function = "bin.lightgbm_.main"
n_seeds = 10

[base_config.data]
cache = false
path = "data/wiki-cs"
setting = "transductive"
add_self_loops = false
num_policy = "none"
external_split = true

[base_config.data.nfa]
num_modes = [
    "mean",
]

[base_config.data.pca.params]
dim = 1000000

[base_config.model]
n_estimators = 4000
n_jobs = 4
verbose = -1
feature_fraction = 0.5257090512938317
lambda_l2 = 0.7962936200032281
learning_rate = 0.00615875774281722
num_leaves = 236
min_sum_hessian_in_leaf = 0.0036334941627573494
bagging_fraction = 0.7697707218704558
stopping_rounds = 1000
device_type = "cpu"

[base_config.fit]
