function = "bin.g2t.g2t_fm.main"
n_seeds = 10

[base_config]
patience = 16
amp = true
n_epochs = -1
epoch_size = 10
min_train_ratio = 0.75
seq_len_pred = 1024
finetune_mode = "full"

[base_config.ensemble]
shuffle_features = true
shuffle_targets = false
n_members = 10

[base_config.tfm]
name = "limix"

[base_config.encodings.lappe]
k = 14

[base_config.encodings.degree]
log = true

[base_config.encodings.pagerank]
log = true

[base_config.nfa]

[base_config.data]
cache = false
path = "data/hm-prices"
setting = "transductive"
internal_split_name = "RL"

[base_config.transform]
labels = true

[base_config.transform.features]
seed = 0
cat_policy = "ordinal"
num_policy = "quantile-normal"
frac_policy = "quantile-uniform"

[base_config.transform.encodings]
num_policy = "quantile-normal"

[base_config.transform.nfa]
seed = 0
cat_policy = "ordinal"
num_policy = "quantile-normal"
frac_policy = "quantile-uniform"

[base_config.optimizer]
type = "AdamW"
lr = 2.320794010302052e-05
weight_decay = 0.0
